services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - infra

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - infra

  consul:
    image: consul:1.15.4
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    ports:
      - 8500:8500
    networks:
      - infra

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: testPassword
    ports:
      - 5434:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - infra
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical" #needed for connector

  mongodb:
    image: mongo:7.0.5-jammy
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: fraud-service
    volumes:
      - dbdata7:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - infra

  connect:
    image: quay.io/debezium/connect:2.6.1.Final
    ports:
      - 8083:8083
#      - 5005:5005
    environment:
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      STATUS_STORAGE_TOPIC: my_connect_statuses
      BOOTSTRAP_SERVERS: kafka:9092

    networks:
      - infra
    links:
      - zookeeper
      - db
    depends_on:
      - kafka
      - zookeeper
      - db

volumes:
  dbdata7:
    driver: local
  pgdata:
    driver: local

networks:
  infra:
    name: shared-infra  # Ensure this name is used consistently across files
    driver: bridge