server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: identity-registry-service
  datasource:
    url: jdbc:postgresql://${INFRASTRUCTURE_HOST:127.0.0.1}:5434/postgres
    username: postgres
    password: testPassword
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  cloud:
    consul:
      discovery:
        enabled: true
      host: ${INFRASTRUCTURE_HOST:127.0.0.1}
      port: 8500

logging:
  pattern:
    correlation: "[ %X{trace_id:-},%X{span_id:-} ] "