server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: credit-cards-service
  datasource:
    url: jdbc:postgresql://${INFRASTRUCTURE_HOST:127.0.0.1}:5434/postgres
    username: postgres
    password: testPassword
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        use_sql_comments: true

  cloud:
    consul:
      discovery:
        enabled: true
      host: ${INFRASTRUCTURE_HOST:127.0.0.1}
      port: 8500
  kafka:
    bootstrap-servers: ${INFRASTRUCTURE_HOST:127.0.0.1}:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        spring.json.add.type.headers: false

logging:
  pattern:
    correlation: "[ %X{trace_id:-},%X{span_id:-} ] "
